{"trial_id": "00", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "units", "default": null, "conditions": [], "min_value": 128, "max_value": 1024, "step": 1, "sampling": "linear"}}], "values": {"units": 906}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"C:\\Users\\ameepaganithage\\Anaconda3\\envs\\Enemy_ship_detection\\lib\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 270, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\ameepaganithage\\Anaconda3\\envs\\Enemy_ship_detection\\lib\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 235, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\ameepaganithage\\Anaconda3\\envs\\Enemy_ship_detection\\lib\\site-packages\\keras_tuner\\engine\\tuner.py\", line 287, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"C:\\Users\\ameepaganithage\\Anaconda3\\envs\\Enemy_ship_detection\\lib\\site-packages\\keras_tuner\\engine\\tuner.py\", line 213, in _build_and_fit_model\n    model = self._try_build(hp)\n  File \"C:\\Users\\ameepaganithage\\Anaconda3\\envs\\Enemy_ship_detection\\lib\\site-packages\\keras_tuner\\engine\\tuner.py\", line 155, in _try_build\n    model = self._build_hypermodel(hp)\n  File \"C:\\Users\\ameepaganithage\\Anaconda3\\envs\\Enemy_ship_detection\\lib\\site-packages\\keras_tuner\\engine\\tuner.py\", line 147, in _build_hypermodel\n    self._override_compile_args(model)\n  File \"C:\\Users\\ameepaganithage\\Anaconda3\\envs\\Enemy_ship_detection\\lib\\site-packages\\keras_tuner\\engine\\tuner.py\", line 176, in _override_compile_args\n    \"loss\": model.loss,\nAttributeError: 'Sequential' object has no attribute 'loss'\n"}